[build-system]
requires = ['setuptools>=42.2',"wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]
[tool.mypy]
mypy_path = "src"
ingore_missing_imports = true